
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spn-meltaier-org
  title: spn-meltaier-org
  description: Service Principal for MeltaierOrg Tenant
  annotations:
    azure.com/clientId: d14f2032-a3e9-40d4-a320-08eb2e910c3c
    azure.com/tenantId: xxxx-xxx-xxxxx-xxxxx-xxxxxxxxx
spec:
  type: servicePrincipal
  lifecycle: experimental
  owner: grp-platform-team
  system: mg-meltaier-org-root

---
