# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: meltaierorg
  title: Azure Entra ID Tenant for MeltaierOrg
  description: Azure Entra ID Tenant for MeltaierOrg
  annotations:
    azure.com/tenantId: xxxx-xxx-xxxxx-xxxxx-xxxxxxxxx
spec:
  type: azureTenant
  lifecycle: experimental
  owner: grp-platform-team
  system: mg-meltaier-org-root

---
